### PR TITLE
[adfile] Fix callee-saved float register definitions: should be SOE

### PR DESCRIPTION
**Pull request by zhengxiaolinX**
Hi team,

We have found unnecessary float register spills before leaf calls and then found callee-saved float registers' definitions should be SOE so the register allocator may firstly use these SOE registers as allocation candidates to prevent spills before leaf calls. I have looked through `F8-F9, F18-F27` usages and found they are not used in any stub so it could be safe. Tested all cases.

Thanks,
Xiaolin

### CODE REVIEW

**Comment by zhengxiaolinX** [comment]
Add more information - this fix is nearly the same as my colleague's patch [JDK-8253048](https://github.com/openjdk/jdk/pull/129) on the aarch64 platform and receives the identical result.

**Review by yadongw — APPROVED** [review]
lgtm

**Review by feilongjiang — CHANGES_REQUESTED** [review]
LGTM, but the comment of Float Register ABI should also be updated according to the new changes.

**Comment by kuaiwei** [comment]
+1

**Review by kuaiwei — APPROVED** [review]
+1

**Comment by zhengxiaolinX** [comment]
> LGTM, but the comment of Float Register ABI should also be updated according to the new changes.

Thanks for the friendly reminder - would you please have another look?

**Review by feilongjiang — APPROVED** [review]

**Pull request merged**
