### PR TITLE
Fix pd_clone_address_expressions: base plus offset addressing mode only

### PR DESCRIPTION
**Pull request by yadongw**
Hi All,

pd_clone_address_expressions should only cover base plus offset addressing mode on rv.
Passed all of the jtreg tests.

Yadong

### CODE REVIEW

**Comment by zhengxiaolinX** [comment]
+1 - though this does not count.

**Review by kuaiwei — APPROVED** [review]
LGTM.
Do you test the impact of this change?

**Comment by yadongw** [comment]
> LGTM.
> Do you test the impact of this change?

Yes, jtreg tests passed.

**Review by yhzhu20 — APPROVED** [review]
LGTM

**Pull request merged**
